# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",

]

# Packages to be installed via the native package manager.
[managers.system]
items = [
  #"base-system",
    "base-devel",
    "cronie",
    "incron",
    "chrony",
    "socklog-void",
    "seatd",
    "polkit",
    "dbus",
  #"dhcpcd",
]

[managers.runit]
items = [
  "cronie", "crond", "chronyd", "nanoklogd", "socklog-unix",
  "seatd", "polkitd", "dbus", "incron", "udevd"
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]

[managers.group]
items = [
  "adrian:2000",
]

[managers.user]
items = [
  "adrian:2000:2000:Adrian:/home/adrian:/bin/bash"
]

[managers.member]
items = [
  "video:adrian",
  "input:adrian",
  "plugdev:adrian",
  "_seatd:adrian",
  "kvm:adrian",
  "libvirt:adrian",
  "docker:adrian",
]
