#!/bin/sh


sudo -E usermod -aG video,input,plugdev,_seatd $USER



echo "en_GB.UTF-8 UTF-8\nen_US.UTF-8 UTF-8" | \
  sudo tee /etc/default/libc-locales > /dev/null


sudo xbps-reconfigure -f glibc-locales

FW_RULESET="./machines/arc.tail9b256.ts.net/etc/iptables/iptables.rules"

if [ -f "$FW_RULESET" ]; then
  echo "[+] FW RULES"
  sudo cp "${FW_RULESET}" /etc/iptables/iptables.rules
fi
