

# --------------------------- #
#    Manager Configuration    #
# --------------------------- #

# Make sure to enter the exact command you use as the normal user!
# That means including 'sudo' or 'doas' or whatever if the command needs it.
# Where you would put items, enter '#:?'.

# Example: add = "sudo apt install #:?"

add = "sudo usrmgr add_member #:?" # Example: sudo apt install #:?
remove = "sudo usrmgr del_member #:?" # Example: sudo apt remove #:?
sync = "" # Example: sudo apt update
upgrade = "" # Example: sudo apt upgrade

plural_name = "system group memberships"

hook_name = "system_group_membership" # This is used in hooks. (Example: post_system_packages_add)

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

# many_args = BOOL: Can you supply many items as an argument? Example: 'sudo apt install git vim wget'

[config]
many_args = false
